# Generated by Django 4.0.4 on 2022-07-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comments_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='num_of_bids',
        ),
    ]
