# Generated by Django 4.0.6 on 2022-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='num_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
