# Generated by Django 4.0.6 on 2022-07-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comments_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('OTHER', 'OTHER'), ('CLOTHING', 'CLOTHING'), ('MAGICAL_ITEM', 'MAGICAL ITEMS'), ('TOYS_KIDS', 'TOYS & KIDS'), ('HEALTH_BEAUTY', 'HEALTH & BEAUTY'), ('FOOD', 'FOOD'), ('WEAPONS', 'WEAPONS'), ('HOUSEHOLD_ITEMS', 'HOUSEHOLD ITEMS')], default='OTHER', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
    ]
